
import { CaseCategory, Court, Settings } from './types';

export const STANFORD_RED = '#8C1515';
export const STANFORD_CHARCOAL = '#231F20';
export const STANFORD_GREEN = '#175E54';

export const JUDGE_VOICE_NAME = 'Charon';

export const COURT_RULE_PRESETS: Record<Court, {
  recommendedTimerMinutes: number;
  recommendedBenchStyle: Settings['benchStyle'];
  addressForm: string;
  formalName: string;
  description: string;
}> = {
  'Generic Appellate Court': {
    recommendedTimerMinutes: 10,
    recommendedBenchStyle: 'Standard',
    addressForm: 'Your Honors',
    formalName: 'a generic intermediate appellate court',
    description: 'A neutral, three-judge appellate panel. A good default for general practice.',
  },
  'U.S. Supreme Court': {
    recommendedTimerMinutes: 15,
    recommendedBenchStyle: 'Hot',
    addressForm: 'Your Honors',
    formalName: 'the United States Supreme Court',
    description: 'A high-stakes argument. Expect a hot bench, hypotheticals, and questions on broad legal doctrine.',
  },
  'U.S. Court of Appeals (Ninth Circuit)': {
    recommendedTimerMinutes: 10,
    recommendedBenchStyle: 'Hot',
    addressForm: 'Your Honors',
    formalName: 'the Ninth Circuit Court of Appeals',
    description: 'A three-judge federal panel. Focus on jurisdiction, standard of review, and binding precedent.',
  },
  'California Supreme Court': {
    recommendedTimerMinutes: 10,
    recommendedBenchStyle: 'Hot',
    addressForm: 'Your Honors',
    formalName: 'the California Supreme Court',
    description: 'State high court. Focus on California statutes, constitutional provisions, and state precedent.',
  },
  'U.S. District Court (Motion Hearing)': {
    recommendedTimerMinutes: 10,
    recommendedBenchStyle: 'Standard',
    addressForm: 'Your Honor',
    formalName: 'a United States District Court',
    description: 'A single judge hearing a motion. Focus on the factual record and procedural standards.',
  },
};


export const CASE_LIBRARY: CaseCategory[] = [
  {
    name: 'Constitutional Law',
    cases: [
      {
        id: 'brown-v-board-of-education-1954',
        title: 'Brown v. Board of Education (1954)',
        year: 1954,
        category: 'Constitutional Law',
        summary: 'The Supreme Court ruled that state-sponsored segregation in public schools is unconstitutional under the Equal Protection Clause of the 14th Amendment, overturning Plessy v. Ferguson and declaring "separate but equal" has no place in education.',
        tags: ['Equal Protection', 'desegregation'],
      },
      {
        id: 'miranda-v-arizona-1966',
        title: 'Miranda v. Arizona (1966)',
        year: 1966,
        category: 'Constitutional Law',
        summary: 'The Court held that police must inform suspects of their Fifth Amendment right against self-incrimination and Sixth Amendment right to counsel before custodial interrogation. This established the famous "Miranda warnings."',
        tags: ['Fifth Amendment', 'Sixth Amendment', 'right to counsel'],
      },
      {
        id: 'roe-v-wade-dobbs-v-jackson-2022',
        title: 'Roe v. Wade (1973) / Dobbs v. Jackson Women\'s Health (2022)',
        year: '1973 / 2022',
        category: 'Constitutional Law',
        summary: 'Roe recognized a constitutional right to abortion under the Due Process Clause. Dobbs overturned Roe, holding there is no constitutional right to abortion and returning the issue to state legislatures.',
        tags: ['Abortion', 'Due Process Clause'],
      },
      {
        id: 'obergefell-v-hodges-2015',
        title: 'Obergefell v. Hodges (2015)',
        year: 2015,
        category: 'Constitutional Law',
        summary: 'The Court ruled that the fundamental right to marry is guaranteed to same-sex couples under the Due Process and Equal Protection Clauses of the 14th Amendment, requiring all states to license and recognize same-sex marriages.',
        tags: ['Same-sex marriage', 'Equal Protection'],
      },
      {
        id: 'district-of-columbia-v-heller-2008',
        title: 'District of Columbia v. Heller (2008)',
        year: 2008,
        category: 'Constitutional Law',
        summary: 'The Court held that the Second Amendment protects an individual\'s right to possess a firearm unconnected with militia service for traditionally lawful purposes like self-defense in the home.',
        tags: ['Second Amendment', 'gun rights'],
      },
    ],
  },
  {
    name: 'Criminal Law',
    cases: [
      {
        id: 'gideon-v-wainwright-1963',
        title: 'Gideon v. Wainwright (1963)',
        year: 1963,
        category: 'Criminal Law',
        summary: 'The Court held that the Sixth Amendment requires states to provide attorneys for criminal defendants who cannot afford their own, establishing the right to counsel in state criminal proceedings.',
        tags: ['Sixth Amendment', 'right to counsel'],
      },
      {
        id: 'terry-v-ohio-1968',
        title: 'Terry v. Ohio (1968)',
        year: 1968,
        category: 'Criminal Law',
        summary: 'Police may conduct a brief investigatory stop ("Terry stop") when they have reasonable suspicion that criminal activity is afoot, and may frisk for weapons if they reasonably believe the person is armed and dangerous.',
        tags: ['Fourth Amendment', 'search and seizure'],
      },
      {
        id: 'batson-v-kentucky-1986',
        title: 'Batson v. Kentucky (1986)',
        year: 1986,
        category: 'Criminal Law',
        summary: 'The use of peremptory challenges to exclude potential jurors solely on the basis of race violates the Equal Protection Clause. Prosecutors must provide race-neutral reasons for striking jurors.',
        tags: ['Jury selection', 'Equal Protection'],
      },
      {
        id: 'crawford-v-washington-2004',
        title: 'Crawford v. Washington (2004)',
        year: 2004,
        category: 'Criminal Law',
        summary: 'The Sixth Amendment\'s Confrontation Clause requires that testimonial statements by witnesses who do not appear at trial may not be admitted unless the witness is unavailable and the defendant had a prior opportunity for cross-examination.',
        tags: ['Sixth Amendment', 'Confrontation Clause'],
      },
    ],
  },
  {
    name: 'Administrative & Regulatory Law',
    cases: [
      {
        id: 'chevron-v-nrdc-1984',
        title: 'Chevron U.S.A. Inc. v. Natural Resources Defense Council (1984)',
        year: 1984,
        category: 'Administrative & Regulatory Law',
        summary: 'Courts must defer to reasonable agency interpretations of ambiguous statutes they administer. This established the two-step Chevron deference framework (overruled by Loper Bright Enterprises v. Raimondo in 2024).',
        tags: ['Chevron deference', 'statutory interpretation'],
      },
      {
        id: 'loper-bright-enterprises-v-raimondo-2024',
        title: 'Loper Bright Enterprises v. Raimondo (2024)',
        year: 2024,
        category: 'Administrative & Regulatory Law',
        summary: 'The Supreme Court overturned Chevron deference, holding that courts must exercise independent judgment in deciding whether an agency has acted within its statutory authority, rather than deferring to agency interpretations.',
        tags: ['Chevron deference', 'statutory interpretation'],
      },
      {
        id: 'massachusetts-v-epa-2007',
        title: 'Massachusetts v. EPA (2007)',
        year: 2007,
        category: 'Administrative & Regulatory Law',
        summary: 'The EPA has authority under the Clean Air Act to regulate greenhouse gas emissions from new motor vehicles if it determines they endanger public health or welfare. States have standing to challenge EPA inaction on climate change.',
        tags: ['Environmental law', 'standing'],
      },
    ],
  },
  {
    name: 'Corporate/Commercial Law',
    cases: [
      {
        id: 'citizens-united-v-fec-2010',
        title: 'Citizens United v. Federal Election Commission (2010)',
        year: 2010,
        category: 'Corporate/Commercial Law',
        summary: 'The First Amendment prohibits government from restricting independent political expenditures by corporations and unions. Corporate funding of independent political broadcasts cannot be limited.',
        tags: ['Campaign finance', 'First Amendment'],
      },
      {
        id: 'basic-inc-v-levinson-1988',
        title: 'Basic Inc. v. Levinson (1988)',
        year: 1988,
        category: 'Corporate/Commercial Law',
        summary: 'Established the "fraud-on-the-market" theory, creating a rebuttable presumption of reliance in securities fraud class actions when plaintiffs allege misrepresentations affected stock prices in efficient markets.',
        tags: ['Securities fraud', 'class action'],
      },
      {
        id: 'att-mobility-v-concepcion-2011',
        title: 'AT&T Mobility v. Concepcion (2011)',
        year: 2011,
        category: 'Corporate/Commercial Law',
        summary: 'The Federal Arbitration Act preempts state laws that prohibit contracts from disallowing class-wide arbitration, allowing companies to require individual arbitration and waive class actions.',
        tags: ['Arbitration', 'class action waiver'],
      },
    ],
  },
  {
    name: 'Intellectual Property Law (Traditional)',
    cases: [
      {
        id: 'diamond-v-chakrabarty-1980',
        title: 'Diamond v. Chakrabarty (1980)',
        year: 1980,
        category: 'Intellectual Property Law (Traditional)',
        summary: 'A live, human-made microorganism is patentable subject matter under 35 U.S.C. § 101. The Court held that "anything under the sun that is made by man" is potentially patentable.',
        tags: ['Patent law', 'biotechnology'],
      },
      {
        id: 'sony-corp-v-universal-city-studios-1984',
        title: 'Sony Corp. v. Universal City Studios (1984)',
        year: 1984,
        category: 'Intellectual Property Law (Traditional)',
        summary: 'Manufacturers of devices capable of substantial non-infringing uses cannot be held liable for contributory infringement even if the devices are also used for infringement. Established the "Betamax defense."',
        tags: ['Copyright', 'fair use'],
      },
      {
        id: 'feist-publications-v-rural-telephone-service-1991',
        title: 'Feist Publications v. Rural Telephone Service (1991)',
        year: 1991,
        category: 'Intellectual Property Law (Traditional)',
        summary: 'Copyright protects only original expression, not facts or compilations of facts arranged in obvious ways. Telephone directory white pages lack sufficient creativity for copyright protection.',
        tags: ['Copyright', 'originality'],
      },
      {
        id: 'alice-corp-v-cls-bank-international-2014',
        title: 'Alice Corp. v. CLS Bank International (2014)',
        year: 2014,
        category: 'Intellectual Property Law (Traditional)',
        summary: 'Abstract ideas implemented on generic computers are not patent-eligible under 35 U.S.C. § 101. Established the two-step Alice/Mayo framework for determining patent eligibility.',
        tags: ['Patent law', 'software patents'],
      },
    ],
  },
  {
    name: 'AI & Technology Cases (Recent)',
    cases: [
      {
        id: 'andersen-v-stability-ai-2023',
        title: 'Andersen v. Stability AI (filed 2023, ongoing)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Visual artists sued AI image generators (Stable Diffusion, Midjourney) alleging copyright infringement and right of publicity violations for using their artwork in training datasets without permission or compensation.',
        tags: ['Copyright Infringement', 'AI training data'],
        status: 'ongoing',
      },
      {
        id: 'nytimes-v-openai-microsoft-2023',
        title: 'The New York Times v. OpenAI & Microsoft (filed December 2023, ongoing)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'The Times alleges OpenAI and Microsoft infringed millions of copyrighted articles to train ChatGPT. The case includes hundreds of examples of ChatGPT allegedly "regurgitating" full articles verbatim, challenging the "fair use" defense.',
        tags: ['Copyright Infringement', 'fair use', 'LLM training'],
        status: 'ongoing',
      },
      {
        id: 'thomson-reuters-v-ross-intelligence-2025',
        title: 'Thomson Reuters v. Ross Intelligence (2020-2025)',
        year: '2020-2025',
        category: 'AI & Technology Cases (Recent)',
        summary: 'Thomson Reuters alleged Ross Intelligence infringed copyrighted Westlaw headnotes and Key Number System to develop an AI legal research tool. In February 2025, the court granted partial summary judgment on direct copyright infringement, rejecting several fair use defenses.',
        tags: ['Copyright Infringement', 'legal tech'],
      },
      {
        id: 'authors-guild-v-openai-meta-2023',
        title: 'Authors Guild (Kadrey, Silverman et al.) v. OpenAI & Meta (2023, ongoing)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Authors including Sarah Silverman sued claiming their books were used to train large language models without permission, allegedly obtained from "shadow libraries" like Library Genesis and Z-Library.',
        tags: ['Copyright Infringement', 'LLM training'],
        status: 'ongoing',
      },
      {
        id: 'universal-music-v-anthropic-2023',
        title: 'Universal Music Group v. Anthropic (filed October 2023)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Major music companies sued Anthropic (maker of Claude) for mass copyright infringement of song lyrics, alleging the company scraped copyrighted lyrics to train its AI without licensing or payment. Trial scheduled for November 2025 in Nashville.',
        tags: ['Copyright Infringement', 'song lyrics'],
        status: 'ongoing',
      },
      {
        id: 'riaa-v-suno-udio-2024',
        title: 'RIAA v. Suno & Udio (filed June 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'First cases against AI music generators for alleged infringement of sound recordings. Record labels claim these services create music that copies protected works. Udio settled with Universal Music Group in October 2025.',
        tags: ['Copyright Infringement', 'generative music'],
      },
      {
        id: 'getty-images-v-stability-ai-2023',
        title: 'Getty Images v. Stability AI (filed 2023, ongoing)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Getty sued Stability AI for allegedly copying and processing millions of Getty-owned images and metadata to train Stable Diffusion, including generating images with distorted Getty watermarks.',
        tags: ['Copyright Infringement', 'image generation'],
        status: 'ongoing',
      },
      {
        id: 'dow-jones-v-perplexity-ai-2024',
        title: 'Dow Jones & Wall Street Journal v. Perplexity AI (filed October 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'News publishers sued Perplexity\'s AI-powered search engine for copyright infringement, focusing on "retrieval-augmented generation" (RAG) that allegedly repackages copyrighted articles into verbatim or near-verbatim summaries.',
        tags: ['Copyright Infringement', 'RAG', 'AI search'],
        status: 'ongoing',
      },
      {
        id: 'mata-v-avianca-2023',
        title: 'Mata v. Avianca (S.D.N.Y. 2023)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Attorney sanctioned for submitting brief citing non-existent cases generated by ChatGPT. The lawyer failed to verify the AI-generated citations, leading to one of the first high-profile "AI hallucination" cases in court.',
        tags: ['AI Hallucination', 'Legal Malpractice'],
      },
      {
        id: 'park-v-kim-2024',
        title: 'Park v. Kim (2d Cir. 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'The Second Circuit referred an attorney to its Grievance Panel for investigation after submitting a brief relying on "non-existent" caselaw generated by ChatGPT.',
        tags: ['AI Hallucination', 'Legal Malpractice'],
      },
      {
        id: 'mobley-v-workday-2023',
        title: 'Mobley v. Workday (filed 2023, N.D. Cal.)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Class action alleging Workday\'s AI-powered hiring software discriminates against job applicants based on age, race, and disability in violation of civil rights laws.',
        tags: ['AI Discrimination', 'hiring'],
        status: 'ongoing',
      },
      {
        id: 'open-communities-v-harbor-group-2024',
        title: 'Open Communities v. Harbor Group (settled 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Fair housing lawsuit alleging Harbor Group\'s AI systems at apartment complexes led to discriminatory outcomes, including blanket rejection of housing voucher applicants. Settled with consent decree requiring fair housing procedures.',
        tags: ['AI Discrimination', 'housing'],
        status: 'settled',
      },
      {
        id: 'sewell-v-openai-2024',
        title: 'Sewell et al. v. OpenAI (filed August 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Parents sued OpenAI after their teen died by suicide, alleging ChatGPT coached him on self-harm methods. Part of at least seven lawsuits claiming ChatGPT drove people to suicide or harmful delusions.',
        tags: ['AI Harmful Outcomes'],
        status: 'ongoing',
      },
      {
        id: 'at-v-openai-l-v-alphabet-2024',
        title: 'A.T. v. OpenAI & Microsoft / L. v. Alphabet (filed 2023, dismissed 2024)',
        year: '2023-2024',
        category: 'AI & Technology Cases (Recent)',
        summary: 'Class actions alleging unlawful collection of personal data from private individuals and unauthorized use to train AI models. Both dismissed, establishing important precedents about data privacy claims against AI companies.',
        tags: ['Data Privacy'],
        status: 'dismissed',
      },
      {
        id: 'baker-v-cvs-health-2024',
        title: 'Baker v. CVS Health Corp (D. Mass. 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Job candidate alleged CVS violated Massachusetts Lie Detector Statute by subjecting them to an AI-based integrity and cultural fit test during interview without proper notification.',
        tags: ['Employment Screening', 'AI hiring'],
      },
      {
        id: 'wex-v-hp-2024',
        title: 'WEX Inc. v. HP Inc. (D. Me. 2024)',
        year: 2024,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Court found that an AI-generated news article indicated potential trademark confusion between WEX and HP\'s "HP WEX" software, granting preliminary injunction. HP argued AI-generated content showed no human confusion, but court disagreed.',
        tags: ['Trademark', 'AI-generated evidence'],
      },
      {
        id: 'bond-v-clover-health-2023',
        title: 'Bond v. Clover Health (M.D. Tenn. 2023)',
        year: 2023,
        category: 'AI & Technology Cases (Recent)',
        summary: 'Class certification granted for securities fraud claims partly based on false statements about Clover Health\'s AI-powered software "Clover Assistant."',
        tags: ['Securities', 'AI representations'],
      },
    ],
  },
  {
    name: 'Additional Landmark Cases',
    cases: [
      {
        id: 'marbury-v-madison-1803',
        title: 'Marbury v. Madison (1803)',
        year: 1803,
        category: 'Additional Landmark Cases',
        summary: 'Established judicial review, giving courts the power to strike down laws that violate the Constitution.',
        tags: ['Judicial review', 'Separation of powers'],
      },
      {
        id: 'plessy-v-ferguson-1896',
        title: 'Plessy v. Ferguson (1896)',
        year: 1896,
        category: 'Additional Landmark Cases',
        summary: 'Upheld "separate but equal" doctrine allowing racial segregation. Overturned by Brown v. Board.',
        tags: ['Equal Protection', 'segregation'],
      },
      {
        id: 'new-york-times-v-sullivan-1964',
        title: 'New York Times v. Sullivan (1964)',
        year: 1964,
        category: 'Additional Landmark Cases',
        summary: 'Public officials must prove "actual malice" to win defamation suits, protecting freedom of the press under the First Amendment.',
        tags: ['First Amendment', 'defamation', 'freedom of the press'],
      },
      {
        id: 'griswold-v-connecticut-1965',
        title: 'Griswold v. Connecticut (1965)',
        year: 1965,
        category: 'Additional Landmark Cases',
        summary: 'Established a constitutional right to privacy, striking down laws prohibiting contraceptive use by married couples.',
        tags: ['Right to privacy'],
      },
      {
        id: 'texas-v-johnson-1989',
        title: 'Texas v. Johnson (1989)',
        year: 1989,
        category: 'Additional Landmark Cases',
        summary: 'Flag burning is symbolic speech protected by the First Amendment, even when offensive.',
        tags: ['First Amendment', 'symbolic speech'],
      },
    ],
  },
];